openapi: "3.0.2"
info:
    title: YaChallenge API
    version: "1.0"
servers:
    - url: http://localhost:8081/
components:
    schemas:
        error:
            type: object
            properties:
                detail:
                    description: error message
                    type: string
            required:
              - detail

        category:
            type: object
            properties:
                id:
                    type: string
                    description: The unique identifier for the category.
                title:
                    type: string
                    description: The title of the category.
                image:
                    type: string
                    description: imgae of the category
            required:
                - id
                - title
                
        user-categories:
          type: object
          properties:
            count:
              type: number
              description: how many categories the user has
            categories:
              type: array
              description: categories that the user has
              items:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  imageUrl:
                    type: string

        user:
            type: object
            properties:
                id:
                    type: string

                email:
                    type: string



                nickname:
                    type: string



                androidToken:
                    type: string
                
            required:
                - id
                - email
                - categories
                - nickname
                
        user-register:
            type: object
            properties:
                id:
                    type: string

                email:
                    type: string

                categories:
                    type: array
                    items:
                        type: string

                nickname:
                    type: string

                password:
                    type: string

                androidToken:
                    type: string
                
            required:
                - id
                - email
                - categories
                - nickname
                - password                
        
        challenge:
            type: object
            properties:
                id:
                    type: string

                title:
                    type: string

                description:
                    type: string

                categoryId:
                    type: string
                categoryTitle:
                    type: string
                
                score:
                    type: number
                imageUrl:
                    type: string


        completedChallenge:
            type: object
            properties:
                id:
                    type: string

                challengeUid: 
                    type: string

                userUid:
                    type: string
                
                score:
                    type: number
                
                createdAt:
                    type: string   
                    
        user-challenges:
          type: object
          properties:
            count:
              type: number
              description: how many categories the user has
            challenges:
              type: array
              description: categories that the user has
              items:
                type: object
                properties:
                  id:
                    type: string

                  title:
                      type: string
  
                  description:
                      type: string
  
                  category:
                      type: string
                      description: "category id"
                  
                  score:
                      type: number
                  imageUrl:
                      type: string          

        user-rankings:
          type: array
          items:
            type: object
            properties:
              score:
                  type: number
                    
              nickname:
                  type: string

paths:
    /v1/categories:
        get:
            description: "get categories"
            responses:
                "200":
                    description: "successfully got categories"
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/category"
            


    /v1/users:
        post:
            description: "create user"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string

                                nickname:
                                    type: string

                                password:
                                    type: string

                                categories:
                                    type: array
                                    items:
                                        type: string

                                androidToken:
                                    type: string
                            required:
                              - email
                              - nickname
                              - password
                              - categories
                                            

            responses:
              '200':
                description: "user was created"
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        id:
                          type: string
                          
                          
                
    /v1/challenges:
        get:
            description: "get challenge"
            parameters:
                - name: category
                  in: query
                  required: false
                  schema:
                        type: string
            responses:
                "200":
                    description: "get challenge"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/challenge"

    /v1/login:
        post:
            description: 'login'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                androidToken:
                                    type: string
                                    
                                email:
                                    type: string

                                password:
                                    type: string

                            required:
                              - email
                              - password
            responses:
              '200':
                description: "user was created"
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        id:
                          type: string
                          
                          
                          
    /v1/users/{id}:
        get:
            description: "get profile"
            parameters:
                - name: id
                  in: path
                  required: true
                  schema: 
                        type: string
                        
            responses:
                    "200": 
                      description: "user profile"
                      content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/user"
        put:
            description: "update user"
            parameters:
              - name: id
                in: path
                required: true
                schema:
                    type: string
            requestBody:
                required: true
                content:
                  application/json:
                    schema:
                        type: object
                        properties:
                            nickname:
                                type: string
                            email:
                                type: string
                            androidToken:
                                type: string

            responses:
                "204":
                    description: "User was updated"
                "400":
                    description: "Invalid request body"
                        
                                
                                
    /v1/users/{id}/categories:
        get:
            description: "getting useers categoreies"
            parameters:
                - name: id
                  in: path
                  required: true
                  schema: 
                        type: string
                        
                        
                    
            responses: 
              "200":
                description: "returns categories that user specified in registration"
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/user-categories"
                      
                      
                      
    /v1/users/rankings/{page}:
        get:
            description: "Get user rankings for a specific page"
            parameters:
                - name: page
                  in: path
                  required: false
                  schema:
                        type: string

            responses:
              "200":
                description: "Successfully got user rankings for the requested page"
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/user-rankings"
                 
                      
                    
                    
    /v1/users/{id}/challenges:
        get:
            description: "getting useers challenges"
            parameters:
                - name: id
                  in: path
                  required: true
                  schema: 
                        type: string
                        
                        
                    
            responses: 
              "200":
                description: "returns challenges that user completed"
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/user-challenges"
          
    /v1/users/{userUid}/challenges/{challengeId}:
    put:
        description: "Mark a challenge as completed for a specific user"
        parameters:
            - name: userUid
              in: path
              required: true
              schema:
                type: string
              description: "Unique identifier of the user"
            - name: challengeId
              in: path
              required: true
              schema:
                type: string
              description: "Unique identifier of the challenge"
        responses:
            "200":
                description: "Challenge marked as completed"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/completedChallenge"
            "400":
                description: "Invalid request parameters"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/error"
            "404":
                description: "User or Challenge not found"
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/error"