components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match


        handler-register-user:
            path: /v1/users
            method: POST
            task_processor: main-task-processor

        handler-update-user-by-id:
            path: /v1/users/{id}
            method: PUT
            task_processor: main-task-processor

        handler-login-user:
            path: /v1/login
            method: POST
            task_processor: main-task-processor
        
        handler-get-categories:
            path: /v1/categories
            method: GET
            task_processor: main-task-processor


        handler-get-challenges:
            path: /v1/challenges
            method: GET
            task_processor: main-task-processor

        handler-v1-users-user:
            path: /v1/users/{id}
            method: GET
            task_processor: main-task-processor

        handler-v1-users-categories:
            path: /v1/users/{id}/categories
            method: GET
            task_processor: main-task-processor
        
        handler-v1-users-challenges:
            path: /v1/users/{id}/challenges
            method: GET
            task_processor: main-task-processor

        handler-v1-users-rankings:
            path: /v1/users/rankings/{page}
            method: GET
            task_processor: main-task-processor

        handler-v1-admin-add-challenge:
            path: /v1/admin/add-challenge
            method: POST
            task_processor: main-task-processor
        
        handler-v1-admin-add-category:
            path: /v1/admin/add-category
            method: POST
            task_processor: main-task-processor
        
        postgres-db-1:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor
